export const DATA_DEMO_ACCOUNTS_SUCCESS = 'DATA_DEMO_ACCOUNTS_SUCCESS'
export const LOAD_DATA_ACCOUNT_INFO_SUCCESS = 'LOAD_DATA_ACCOUNT_INFO_SUCCESS'

export const CHANGE_LOAD_DEMO_ACCOUNTS_IN_PROGRESS = 'CHANGE_LOAD_DEMO_ACCOUNTS_IN_PROGRESS'
export const CHANGE_LOAD_REAL_ACCOUNTS_IN_PROGRESS = 'CHANGE_LOAD_REAL_ACCOUNTS_IN_PROGRESS'
export const CHANGE_LOAD_INFO_ACCOUNTS_IN_PROGRESS = 'CHANGE_LOAD_INFO_ACCOUNTS_IN_PROGRESS'

export const DATA_REAL_ACCOUNTS_SUCCESS = 'DATA_REAL_ACCOUNTS_SUCCESS'

export const CHANGE_SELECTED_OPEN_ACCOUNT_TYPE = 'CHANGE_SELECTED_OPEN_ACCOUNT_TYPE'
export const CHANGE_SELECTED_LEVERAGE = 'CHANGE_SELECTED_LEVERAGE'
export const CHANGE_CURRENCY_ACCOUNT = 'CHANGE_CURRENCY_ACCOUNT'
